# Generated by Django 5.0.3 on 2024-03-15 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_cost',
            new_name='cost',
        ),
    ]
